# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_team_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='assists',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='goals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='saves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='shots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
