# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20160129_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-player_last_name', 'player_first_name']},
        ),
    ]
