# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20160211_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='summary',
            field=models.TextField(default='Game'),
        ),
    ]
