# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 01:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.TimeField(default=datetime.date.today)),
                ('text', models.TextField()),
                ('currently_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
