# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=8)),
                ('home_team_score', models.PositiveSmallIntegerField()),
                ('away_team_score', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField()),
                ('assists', models.PositiveIntegerField()),
                ('saves', models.PositiveIntegerField()),
                ('shots', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Game')),
            ],
        ),
        migrations.CreateModel(
            name='GameWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='player',
            name='player_nickname',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='gameweek',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Season'),
        ),
        migrations.AddField(
            model_name='gamestats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='stats.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='gameweek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.GameWeek'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='stats.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stats.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='gameweek',
            unique_together=set([('season', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='gamestats',
            unique_together=set([('game', 'player')]),
        ),
    ]
