# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20160116_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='series_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
